/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.unimontes.ccet.dcc.pg1.view.paineis;

import br.unimontes.ccet.dcc.pg1.controller.AlunoController;
import br.unimontes.ccet.dcc.pg1.controller.AlunosMateriasController;
import br.unimontes.ccet.dcc.pg1.controller.CursoController;
import br.unimontes.ccet.dcc.pg1.model.dao.exception.DAOexception;
import br.unimontes.ccet.dcc.pg1.model.entity.Aluno;
import br.unimontes.ccet.dcc.pg1.model.entity.Curso;
import java.awt.Color;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author maylo
 */
public class AlterarAluno extends javax.swing.JPanel {

    /**
     * Creates new form AlterarAluno
     */
    public AlterarAluno() {
        initComponents();
        try {
            DefaultTableModel tableModel = (DefaultTableModel) TabelaAluno.getModel();
            tableModel.setRowCount(0);
            AlunoController alunoController = new AlunoController();
            CursoController cursoController = new CursoController();
            ArrayList<Aluno> alunos = alunoController.findAll();
            alunos.forEach((Aluno aluno) -> {

                tableModel.addRow(new Object[]{aluno.getMatricula(), aluno.getNome(), aluno.getDataNascimento(), aluno.getEmail(), aluno.getTelefone(), aluno.getEndereço()});
            });
            TabelaAluno.setModel(tableModel);
        } catch (SQLException | DAOexception ex) {
            System.out.println("ERROR: " + ex);

        } catch (NumberFormatException ex) {
            System.out.println("ERROR: " + ex);
        }

        TableActionEvent event = new TableActionEvent() {
            @Override
            public void onEdit(int row) {
                PainelExcluir.removeAll();
                PainelExcluir.repaint();
                PainelExcluir.revalidate();
                Aluno a = new Aluno();
                a.setMatricula((String) TabelaAluno.getValueAt(TabelaAluno.getSelectedRow(), 0));
                a.setNome((String) TabelaAluno.getValueAt(TabelaAluno.getSelectedRow(), 1));
                a.setDataNascimento((String) TabelaAluno.getValueAt(TabelaAluno.getSelectedRow(), 2));
                a.setEmail((String) TabelaAluno.getValueAt(TabelaAluno.getSelectedRow(), 3));
                a.setTelefone((String) TabelaAluno.getValueAt(TabelaAluno.getSelectedRow(), 4));
                a.setEndereço((String) TabelaAluno.getValueAt(TabelaAluno.getSelectedRow(), 5));
                AlterarDadosAluno alterar = new AlterarDadosAluno(a);
                alterar.setSize(760, 471);
                PainelExcluir.add(alterar);
                PainelExcluir.repaint();
                PainelExcluir.revalidate();
            }

            @Override
            public void onDelete(int row) {

                int resultado = JOptionPane.showConfirmDialog(null, "Deseja excluir o aluno ?", "Excluir aluno", 0);
                if (resultado == JOptionPane.YES_OPTION) {
                    row = TabelaAluno.getSelectedRow();

                    try {
                        DefaultTableModel tableModel = (DefaultTableModel) TabelaAluno.getModel();
                        AlunoController alunoController = new AlunoController();
                        String matricula = "" + tableModel.getValueAt(row, 0);
                        alunoController.delete(matricula);
                        AlunosMateriasController.deleteFrommatricula(matricula);

                        JOptionPane.showMessageDialog(null, "Aluno Removido");
                        tableModel.removeRow(row);
                    } catch (NumberFormatException ex) {
                        System.out.println("ERROR: " + ex);
                    } catch (DAOexception ex) {
                        System.out.println("ERROR: " + ex);
                    } catch (SQLException ex) {
                        System.out.println("ERROR: " + ex);
                    }
                }

            }

            @Override
            public void onView(int row) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        };
        TabelaAluno.getColumnModel().getColumn(6).setCellRenderer(new TableActionCellRender());
        TabelaAluno.getColumnModel().getColumn(6).setCellEditor(new TableActionCellEditor(event));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        PainelExcluir = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        logoprincipal = new javax.swing.JLabel();
        jSeparator6 = new javax.swing.JSeparator();
        BotaoVoltar = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new raven.scroll.win11.ScrollPaneWin11();
        TabelaAluno = new javax.swing.JTable();
        add = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        PainelExcluir.setBackground(new java.awt.Color(255, 255, 255));
        PainelExcluir.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Roboto Medium", 0, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Dados dos Alunos");
        PainelExcluir.add(jLabel1);
        jLabel1.setBounds(60, 50, 385, 40);

        logoprincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/LOGONOVA.png"))); // NOI18N
        PainelExcluir.add(logoprincipal);
        logoprincipal.setBounds(530, 40, 180, 70);
        PainelExcluir.add(jSeparator6);
        jSeparator6.setBounds(60, 310, 347, 0);

        BotaoVoltar.setBackground(new java.awt.Color(1, 181, 214));
        BotaoVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BotaoVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BotaoVoltarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BotaoVoltarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BotaoVoltarMouseExited(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 10)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("VOLTAR");

        javax.swing.GroupLayout BotaoVoltarLayout = new javax.swing.GroupLayout(BotaoVoltar);
        BotaoVoltar.setLayout(BotaoVoltarLayout);
        BotaoVoltarLayout.setHorizontalGroup(
            BotaoVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BotaoVoltarLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
        );
        BotaoVoltarLayout.setVerticalGroup(
            BotaoVoltarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BotaoVoltarLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        PainelExcluir.add(BotaoVoltar);
        BotaoVoltar.setBounds(6, 10, 49, 25);

        TabelaAluno.setBackground(new java.awt.Color(255, 255, 255));
        TabelaAluno.setFont(new java.awt.Font("Roboto", 0, 12)); // NOI18N
        TabelaAluno.setForeground(new java.awt.Color(0, 0, 0));
        TabelaAluno.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Matricula", "Nome", "Nascimento", "Email", "Telefone", "Endereço", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        TabelaAluno.setFocusable(false);
        TabelaAluno.setGridColor(new java.awt.Color(255, 255, 255));
        TabelaAluno.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TabelaAluno.setRowHeight(40);
        TabelaAluno.setSelectionBackground(new java.awt.Color(1, 181, 214));
        TabelaAluno.setSelectionForeground(new java.awt.Color(255, 255, 255));
        TabelaAluno.setShowVerticalLines(false);
        TabelaAluno.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(TabelaAluno);
        if (TabelaAluno.getColumnModel().getColumnCount() > 0) {
            TabelaAluno.getColumnModel().getColumn(0).setPreferredWidth(40);
            TabelaAluno.getColumnModel().getColumn(2).setPreferredWidth(30);
            TabelaAluno.getColumnModel().getColumn(3).setPreferredWidth(100);
            TabelaAluno.getColumnModel().getColumn(6).setPreferredWidth(50);
        }

        PainelExcluir.add(jScrollPane1);
        jScrollPane1.setBounds(6, 131, 720, 270);

        add.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        add.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Novo Projeto (14).png"))); // NOI18N
        add.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        add.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addMouseClicked(evt);
            }
        });
        PainelExcluir.add(add);
        add.setBounds(630, 410, 60, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 736, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 462, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(PainelExcluir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVoltarMouseClicked
        PainelExcluir.removeAll();
        PainelExcluir.repaint();
        PainelExcluir.revalidate();
        AreaAlteraçõesSecretaria alteracoes = new AreaAlteraçõesSecretaria();
        alteracoes.setSize(760, 471);
        PainelExcluir.add(alteracoes);
        PainelExcluir.repaint();
        PainelExcluir.revalidate();
    }//GEN-LAST:event_BotaoVoltarMouseClicked

    private void BotaoVoltarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVoltarMouseEntered
        BotaoVoltar.setBackground(new Color(170, 208, 215));
    }//GEN-LAST:event_BotaoVoltarMouseEntered

    private void BotaoVoltarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BotaoVoltarMouseExited
        BotaoVoltar.setBackground(new Color(1, 181, 214));
    }//GEN-LAST:event_BotaoVoltarMouseExited

    private void addMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addMouseClicked
        PainelExcluir.removeAll();
        PainelExcluir.repaint();
        PainelExcluir.revalidate();
        CadastrarNovoAluno cadastrar = new CadastrarNovoAluno();
        cadastrar.setSize(760, 471);
        PainelExcluir.add(cadastrar);
        PainelExcluir.repaint();
        PainelExcluir.revalidate();
    }//GEN-LAST:event_addMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotaoVoltar;
    private javax.swing.JPanel PainelExcluir;
    private javax.swing.JTable TabelaAluno;
    private javax.swing.JLabel add;
    private javax.swing.JLabel addAluno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JLabel logoprincipal;
    // End of variables declaration//GEN-END:variables
}
